### ISSUE TITLE
what postcss/webpack config?

### ISSUE THREAD

**Issue by ianstormtaylor** [lowmess/tachyons-columns#1]
@lowmess what webpack or postcss config is this used with to get:

```
@import 'tachyons-columns';
```

...to work properly? 

Everything I'm trying tries to resolve it relatively and fails.

**Comment by lowmess** [comment]
Unfortunately, `tachyons-cli` doesn't create an `index.css` file. So what [I typically do](https://github.com/lowmess/metalsmith-resume/blob/master/css/main.css#L51) is use `postcss-import` and then call the file more explicitly:

``` css
@import 'tachyons-columns/css/tachyons-columns.css';
```

It's a little annoying, but it works. Hope this helps!
